Installing Numpy 

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


Importing numpy

In [1]:
import numpy as np

Checking Version of Numpy

In [6]:
 np.__version__

'2.4.6'

Creating Array 


In [5]:
a = np.array([1 , 2, 3]) # 1D array 
b = np.array([[4, 5, 6], [7, 8, 9]]) # 2D array 
c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) # 3D array 

Displaying array

In [ ]:
print("Displaying first array:", a )
print("Displaying Second array:", b)
print("Displaying third array:", c)

Displaying first array: [1 2 3]
Displaying Second array: [[4 5 6]
 [7 8 9]]
Displaying Second array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


1D, 2D & 3D array

In [6]:
print("Dimension of array a is: ", a.ndim )
print("Dimension of array b is: ", b.ndim  )
print("Dimension of array c is: ", c.ndim  )

Dimension of array a is:  1
Dimension of array b is:  2
Dimension of array c is:  3


UseFull functions for creating arrays

In [ ]:
# np.zeros mean creating array that is filled with zeros 
c = np.zeros([2, 4]) # In the square bracket, the first one represent rows and the second one represent columns
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
#np.ones mean creating array that is filled with ones 
d = np.ones([1, 2])
print(d)

[[1. 1.]]


In [8]:
# Creates an array where every element is a specific value.
e = np.full([2, 2], 7)
print(e)

[[7 7]
 [7 7]]


In [32]:
#Creates an identity matrix.
f = np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [9]:
# Creating array with a sequence of number
g = np.arange(4, 15, 0.5) # The first number is the starting point, the second number is the finist point and the thirs is the steps 
print(g)

[ 4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5
 11.  11.5 12.  12.5 13.  13.5 14.  14.5]


Calculating Mean, Median, Min, Max 

In [60]:
data = np.array([1, 2, 3, 4, 5, 6 ])
print("Mean :", data.mean())
print("Median :", np.median(data))
print("Min :", data.min())
print("Max :", data.max())

Mean : 3.5
Median : 3.5
Min : 1
Max : 6


Numpy Propertise

In [44]:
print("Shape: ", g.shape )     # dimensions
print("Dimension: ", g.ndim )      # number of dimensions
print("Total number of elements: ", g.size )      # total number of elements
print("Data type of the array: ", g.dtype  )    # data type

Shape:  (5,)
Dimension:  1
Total number of elements:  5
Data type of the array:  int64


Array operations 
Sum & Multiply

In [47]:
print("Sum of a and b is:" ,a + b )
print("MUltiplications of a and b is :", a * b)

Sum of a and b is: [[ 5  7  9]
 [ 8 10 12]]
MUltiplications of a and b is : [[ 4 10 18]
 [ 7 16 27]]


Subtraction & Division

In [ ]:
print("Subtraction of a and b is:" ,a - b )
print("Division of a and b is :", a / b)

Su btraction of a and b is: [[-3 -3 -3]
 [-6 -6 -6]]
Division of a and b is : [[0.25       0.4        0.5       ]
 [0.14285714 0.25       0.33333333]]
