In [1]:
import numpy as np

Indexing in Numpy 1D array

In [ ]:
a = np.array([1, 2, 3, 4])
print(a[0]) 
# Indexing of numpy is same as in python 

1


In [ ]:
print(a[2]) # in array --> Numbering start from 0 
print(a[3])

3
4


Accessing 2D array 

In [ ]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # The first array is 0 and second 1 but if we want to select specifin number than two square bracket will be used
print(b[0]) # 0 Representing the first array

[1 2 3 4]


In [7]:
print(b[0][1]) # 0 --> first array and 1 --> mean inside the firsr array second element

2


Accessing 3D array

In [43]:
c = np.array([[[1, 2, 3], [3, 4, 5 ], [6, 7, 8]]])
print(c[0][0]) #Take the first matrix → c[0] ,Take the first matrix → c[0]
print(c[0][0][1])

[1 2 3]
2


Array slicing --> Positive Indexing


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6 ,7]) # Slicing mean selecting specific values 
print(arr[1:5]) # The first one is the starting index and last one is stopping index

[2 3 4 5]


In [26]:
print(arr[0 : 5 : 2]) # In this slicing the first one is the starting point, the second one is the stopping and the last one is the steps

[1 3 5]


In [ ]:
print(arr[:]) # TThis mean from starting --> Ending 
print(arr[:3]) # Tis mean starting to the index 3 

[1 2 3 4 5 6 7]
[1 2 3]


Negative Indexing

In [33]:
print(arr[-3 : -1]) # In array -1 is the last element and so on we count in array 

[5 6]


In [34]:
print(arr[ : -1])

[1 2 3 4 5 6]


In [37]:
print(arr[ :: 2]) # This is the same, as we saw in (2 : 4 : 2)
# It refer to start from zero and go to end and take steps of 2

[1 3 5 7]


Array Filtering/ Boolean Masking

In [ ]:
arr = np.array([1, 2, 3, 4])
x = [True, False, True, False] # True --> 1 False --> 0
new = arr[x] 
print(new)

[1 3]


Filtering array 

In [ ]:
arr = np.array([1, 5, 10, 51,  15, 25, 35 ,42, 45, 48, 49, 52])

filter_array = []

for i in arr:
    if(i > 42):
        filter_array.append(True)
    else:
        filter_array.append(False)
     
new_arr = arr[filter_array]

print(filter_array)
print(new_arr)       

[False, False, False, True, False, False, False, False, True, True, True, True]
[51 45 48 49 52]


Filtering Array of Even & Odd elements 

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6])

even_arr = []

for i in arr:
    if( i % 2 == 0):
        even_arr.append(True)
    else:
        even_arr.append(False)

new_arr = arr[even_arr]
print(even_arr)
print(new_arr)

[False, True, False, True, False, True]
[2 4 6]
